# Docker Compose del launcher con microservicios y bases de datos PostgreSQL dedicadas.
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=raunogroch-pg
      - POSTGRES_PASSWORD=Passw0rd.3315
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  gateway-ms-dev:
    build:
      context: ./clubs-gateway-microservice
      dockerfile: Dockerfile
    ports:
      - ${GATEWAY_PORT}:3000
    volumes:
      - ./clubs-gateway-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    depends_on:
      - nats-server
    restart: unless-stopped
    environment:
      - PORT=3000
      - CORS_ORIGIN=*
      - NATS_SERVERS=nats://nats-server:4222

  users-ms-dev:
    build:
      context: ./clubs-users-microservice
      dockerfile: Dockerfile
    depends_on:
      - nats-server
      - postgres
    volumes:
      - ./clubs-users-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    restart: unless-stopped
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://raunogroch-pg:Passw0rd.3315@postgres:5432/usuariosdb-dev
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_SECRET=EsT0D3betterTh4nThis

  assignments-ms-dev:
    build:
      context: ./clubs-assignments-microservice
      dockerfile: Dockerfile
    depends_on:
      - nats-server
      - postgres
    volumes:
      - ./clubs-assignments-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    restart: unless-stopped
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://raunogroch-pg:Passw0rd.3315@postgres:5432/assignmentsdb-dev
      - NATS_SERVERS=nats://nats-server:4222

  clubs-ms-dev:
    build:
      context: ./clubs-clubs-microservice
      dockerfile: Dockerfile
    depends_on:
      - nats-server
      - postgres
    volumes:
      - ./clubs-clubs-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    restart: unless-stopped
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://raunogroch-pg:Passw0rd.3315@postgres:5432/clubsdb-dev
      - NATS_SERVERS=nats://nats-server:4222

  groups-ms-dev:
    build:
      context: ./clubs-groups-microservice
      dockerfile: Dockerfile
    depends_on:
      - nats-server
      - postgres
    volumes:
      - ./clubs-groups-microservice/src:/usr/src/app/src
    command: pnpm run start:dev
    restart: unless-stopped
    environment:
      - PORT=3004
      - DATABASE_URL=postgresql://raunogroch-pg:Passw0rd.3315@postgres:5432/groupsdb-dev
      - NATS_SERVERS=nats://nats-server:4222

volumes:
  postgres_data:
